### ISSUE TITLE
DeWitt v De Witt

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#10]
the search returns 2 DeWitt counties.
De Witt only returns NAIP 2014 CCM.
DeWitt returns all other data.

![dewitt2](https://cloud.githubusercontent.com/assets/8459928/7454619/16fb10e2-f23b-11e4-8fbe-9e092d3b1d68.PNG)
![de witt](https://cloud.githubusercontent.com/assets/8459928/7454617/16f70178-f23b-11e4-9741-5930e0d3ac62.PNG)
![dewitt](https://cloud.githubusercontent.com/assets/8459928/7454618/16f91d50-f23b-11e4-8d93-3da77829f5fb.PNG)

**Comment by jseppi** [comment]
nice catch

**Comment by wilsaj** [comment]
@mitchellryant you ok with changing everything over to "DeWitt"? Seems to more correct - is the ANSI standard spelling and what they are using on their official website: http://www.co.dewitt.tx.us/

**Comment by wilsaj** [comment]
![Do it](http://i.giphy.com/wi8Ez1mwRcKGI.gif)
