### ISSUE TITLE
NAIP 2014 La Joya DOQQs missing

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#12]
![lajoya](https://cloud.githubusercontent.com/assets/8459928/7518171/0d20ca60-f49f-11e4-85db-42fa8aba79ba.PNG)

We have data for previous years for most of the quad.

**Comment by mitchellryant** [comment]
https://38.media.tumblr.com/tumblr_m9e20lBDCG1r24z09o1_500.gif

**Comment by jseppi** [comment]
I think you mean

![](https://38.media.tumblr.com/tumblr_m9e20lBDCG1r24z09o1_500.gif)

**Comment by mitchellryant** [comment]
yes i was hoping git would treat it differently, but i failed

**Comment by wilsaj** [comment]
Same situation as #13

**Comment by wilsaj** [comment]
done
