### ISSUE TITLE
NRCS Soils Modified

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#22]
Can we add the Soils data to the Data Download?  It will be at both the state and county level.

s3://tnris-datadownload/d/nrcs-soils
http://tnris-datadownload.s3-website-us-east-1.amazonaws.com/nrcs-soils/

**Comment by wilsaj** [comment]
Sure - what do you want to use for the category and download link text?

**Comment by mitchellryant** [comment]
Im thinking it can go in the Natural Regions Category. The Link text should be NRCS Soils Simplified or NRCS Soils Modified
