### ISSUE TITLE
Add TxDOT Roads at County level

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#30]
I extracted the txdot roadways by county and loaded them to s3. hopefully i name them correctly. can you add the data download 'db'.

**Comment by wilsaj** [comment]
the dataset code part of the file names are incorrect:
`d/txdot-roads/county/48507/txdot-roadways-2014_48507.zip` 
should be
`d/txdot-roads/county/48507/txdot-roads-2014_48507.zip`

**Comment by mitchellryant** [comment]
i knew i was jack something up. problem has been corrected.

**Comment by wilsaj** [comment]
it should actually be
`d/txdot-roads/county/48507/txdot-roads_48507.zip`

sorry for giving you bad info the first time :do_not_litter:

**Comment by mitchellryant** [comment]
i think we are good now renamed them. 

![mushroom](https://cloud.githubusercontent.com/assets/8459928/9943132/2af6850c-5d45-11e5-8ef9-11f80de4cf55.gif)

![dancemachine](https://cloud.githubusercontent.com/assets/8459928/9943106/05369b40-5d45-11e5-89a4-3fd46afb1cb1.gif)

![mad-max-tom-hardy-thumbs-up](https://cloud.githubusercontent.com/assets/8459928/9943122/1fbc8056-5d45-11e5-9a28-1552f72e1b3b.gif)
