### ISSUE TITLE
Update Data Download to add 5ft Contours, HPIDS 15 6in, and TOP 15 50cm

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#36]
Please add the following data sets to the data download?

County level - Compressed County Mosaics
- [x] top15-nc-cir-50cm

Quad - Elevation
- [ ] capcog-2007-5ft
- [ ] capcog-2008-5ft
- [ ] fema-2011-5ft
- [ ] fema-2013-5ft
- [ ] ibwc-2011-5ft
- [ ] lcra-2007-5ft
- [ ] tnris-2009-5ft
- [ ] tnris-2010-5ft
- [ ] tnris-2011-5ft
- [ ] tnris-2012-5ft
- [ ] tnris-2013-5ft
- [ ] tnris-2014-5ft
- [ ] tpwd-2014-5ft

Quarter Quad
- [x] hpids15-nc-cir-6in-georgetown
- [x] top15-nc-cir-50cm

**Comment by wilsaj** [comment]
per discussion, waiting on rename of elevation data codes: `capcog-2007-5ft` -> `capcog-2007-5ft-contours'

**Comment by mitchellryant** [comment]
all contour zips have been renamed
