### ISSUE TITLE
Change wording for Historic Imagery on Data Download

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#37]
Can we look into change the wording for Historic Imagery on Data Download, to better clarify completeness of "available" data?

Maybe something like this 

Within the TNRIS archives there is Historical Aerial Imagery of *** County for the following years: ***.  Coverage for a particular County may not be complete and may also include photo indices. The imagery is not available online, but you can use the Order Data form to determine coverage for any of the historical imagery.

**Comment by jseppi** [comment]
Yeah, no problem. What does "include photo indices" mean?
