### ISSUE TITLE
OSM in Data Download

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#38]
@jseppi and @wilsaj what is the possibility of getting an OSM extract for Texas into the data download? problems related to doing this?

**Comment by jseppi** [comment]
Technically it wouldn't be too bad, but OSM is under a more restrictive license than the public domain that our data is under. There are already sites that have periodic extracts (such as http://download.geofabrik.de/north-america/us/texas.html).

**Comment by wilsaj** [comment]
I love OSM, but I'm a soft :-1: on this. 

The geofabrik and mapzen extracts are great as is, and pointing people to those extracts is more empowering to users since they can use that as a tool to get OSM data for anywhere else on Earth (not just Texas).

**Comment by mitchellryant** [comment]
as discussed this @jseppi and @wilsaj, i will add an OSM entry to the data catalog.
