### ISSUE TITLE
data download: River and Streams

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#56]
Can you change the Description text to include water bodies?

Maybe **Rivers, Streams and Waterbodies**

![image](https://cloud.githubusercontent.com/assets/8459928/12460402/1e6b21e4-bf79-11e5-9b33-652e84a1d290.png)

**Comment by jseppi** [comment]
or **Rivers, Streams, and Waterbodies**

**Comment by wilsaj** [comment]
what about **Rivers, Streams, and Warbleblobbies** ?
