### ISSUE TITLE
add data: HPIDS 2015 TPWD

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#63]
The HPIDS 2015 TPWD data has been added to the s3 bucket. Could you please added it to the download db?

it is 3 separate datasets
hpids15-nc-cir-6in-tpwd-hiddenpines
hpids15-nc-cir-6in-tpwd-huecotanks
hpids15-nc-cir-6in-tpwd-powderhornranch

**Comment by wilsaj** [comment]
@mitchellryant directory structure is off for hiddenpines (need to be in individual qquad directories), and I'm not seeing huecotanks or powederhornranch

**Comment by wilsaj** [comment]
done

**Comment by mitchellryant** [comment]
The Hueco Tanks and PowerHorn Ranch dataset were incorrectly labeled 6in instead of 12in. Data on local file system was renamed, re-compressed, and loaded to new keys on s3

hpids15-nc-cir-12in-tpwd-huecotanks
hpids15-nc-cir-12in-tpwd-powderhornranch

Also the label on the download app is incorrect **TWPD** instead of **TPWD**.

![image](https://cloud.githubusercontent.com/assets/8459928/14441545/e427e82e-fffa-11e5-92eb-ddbb4326a58f.png)

**Comment by wilsaj** [comment]
@mitchellryant  s hiddenpines still 6in? or was does that need to be changed as well?
