### ISSUE TITLE
Add\Remove Datasets from DataDownload

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#89]
Please remove:
- [x] the statewide OTLS, i do not believe it is stored in the DB.
- [x] - code: tnris-2009-5ft-contours (Data is duplicated within lidar downloads)
- [x] - code: tnris-2010-5ft-contours (Data is duplicated within lidar downloads)
- [x] - code: tnris-2011-5ft-contours (Data is duplicated within lidar downloads)
- [x] - code: tnris-2012-5ft-contours (Data is duplicated within lidar downloads)
- [x] - code: tnris-2013-5ft-contours (Data is duplicated within lidar downloads)
- [x] - code: tnris-2014-5ft-contours (Data is duplicated within lidar downloads)
- [x] - code: tnris-2015-5ft-contours (Data is duplicated within lidar downloads)

Please add:
- [x] stratmap-2017-central-texas-lidar https://github.com/TNRIS/tnris.org/issues/1504
`- code: stratmap17-50cm-central-texas
  displayName: '2017 StratMap Central Texas 50cm Lidar'
  entry: 'stratMap-2017-50cm-central-texas-lidar'`

**Comment by adambreznicky** [comment]
all completed via commit 1948252508c3aa158172385488fd26952d7d63b6

statewide otls was in database. removed it and all tnris contour datasets listed. added central texas lidar 2017
