### ISSUE TITLE
Add StratMap 2017 Jefferson\Liberty Lidar

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#90]
Add StratMap 2017 Jefferson\Liberty Lidar to datadownload.

https://github.com/TNRIS/tnris.org/issues/1534

**Comment by mitchellryant** [comment]
data has loaded to s3 location. ready to be added.

**Comment by adambreznicky** [comment]
both datasets added via commit e2bd201e24e09ffc47a1d428b51eb83600ff5e06
