### ISSUE TITLE
Add new Lidar datasets to download.

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#91]
code: usgs14-70cm-archer-jack
displayName: '2014 USGS Archer\Jack 70cm Lidar'
entry: 'usgs-2014-70cm-archer-jack'

code: usgs16-70cm-middle-brazos-lake-whitney
displayName: '2016 USGS Middle Brazos\Lake Whitney 70cm Lidar'
entry: 'usgs-2016-70cm-middle-brazos-lake-whitney'

code: usgs16-70cm-neches-river-basin
displayName: '2016 USGS Neches River Basin 70cm Lidar'
entry: 'usgs-2016-70cm-neches-river-basin'

code: usgs17-70cm-amistad-nra
displayName: '2017 USGS Amistad NRA 70cm Lidar'
entry: 'usgs-2017-70cm-amistad-nra'

code: stratmap18-50cm-crockett
displayName: '2018 StratMap Crockett 50cm Lidar'
entry: 'stratmap18-50cm-crockett'

**Comment by adambreznicky** [comment]
added to database and redeployed. these datasets are now live. may they live long and prosper.
commit #83d06f8274f372147ac045dd2866c479f0909890

**Comment by mitchellryant** [comment]
all data for usgs 2014 Jack\Archer and been zipped and reloaded to s3. existing data needs to be removed and new data added.

**Comment by adambreznicky** [comment]
Updated and deployed
