### ISSUE TITLE
fix stratmap18-nc-cir-caparea-mclennan

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data-download#93]
This should correct the issues i created by mis-naming the data. 

code: stratmap18-nc-cir-caparea
displayName: 'StratMap 2018 CAP-Area/McLennan NC/CIR'
entry: 'stratmap18-nc-cir-caparea-mclennan'

**Comment by adambreznicky** [comment]
resolved c71f46ab415a9c52a0c3c55b46c2ca388d62c042
